import { z } from "zod";

export const templateSectorSchema = z.enum([
  "teknoloji",
  "farma",
  "lojistik",
  "gym",
  "enerji",
  "startup",
  "insaat",
  "tasimacilik",
  "danismanlik",
  "oto-yikama",
  "butik",
]);

export const templateSchema = z.object({
  id: z.string(),
  slug: z.string(),
  title: z.string(),
  sector: templateSectorSchema,
  summary: z.string(),
  features: z.array(z.string()).min(3),
  deliveryTime: z.string(),
  startingPrice: z.string(),
  image: z.string(),
  /** Netlify veya canlı demo URL; varsa kartta "Canlı Demo" butonu çıkar */
  demoUrl: z.string().url().optional(),
});

const rawTemplates = [
  {
    id: "tpl-teknoloji",
    slug: "teknoloji",
    title: "Teknoloji",
    sector: "teknoloji",
    summary:
      "Teknoloji ve yazılım firmaları için kurumsal site: koyu tema, 3D ve hareketli görsel efektler, çok sayfalı kurumsal mimari.",
    features: [
      "Premium tasarım: 3D / motion efektler ve akıcı geçişler",
      "Hizmetler, ürünler, referanslar, iletişim ve yasal sayfalar",
      "Türkçe / İngilizce çift dil seçeneği",
      "Hızlı yüklenir; mobil ve Google uyumlu (Core Web Vitals)",
    ],
    deliveryTime: "5–7 gün",
    startingPrice: "₺28.000",
    image: "/images/cases/korsis-teknoloji.png",
    demoUrl: "https://adorable-torrone-84b065.netlify.app/",
  },
  {
    id: "tpl-farma",
    slug: "farma",
    title: "İlaç & Sağlık",
    sector: "farma",
    summary: "İlaç, medikal ürün ve sağlık firmaları için kurumsal çok sayfalı site şablonu; ürün vitrini ve bilim kurulu içerikleriyle.",
    features: [
      "8+ sayfa (ana, ürünler, detay, bilim kurulu, hakkımızda, iletişim, gizlilik & KVKK)",
      "Ürün vitrini ve kurumsal içerik blokları",
      "İletişim ve bilgi talep formları",
      "Next.js + TypeScript altyapısı; mobil uyumlu, teknik SEO dahil",
    ],
    deliveryTime: "4–5 gün",
    startingPrice: "₺22.000",
    image: "/images/cases/dedpharma.png",
    demoUrl: "https://charming-jelly-c2ba89.netlify.app",
  },
  {
    id: "tpl-lojistik",
    slug: "lojistik",
    title: "Lojistik",
    sector: "lojistik",
    summary: "Lojistik ve taşımacılık firmaları için dönüşüm odaklı kurumsal web sitesi; hizmet kapsamı, teklif formu ve WhatsApp entegrasyonu.",
    features: [
      "Hizmet rotaları, kapsama alanı ve kurumsal sözleşme bölümleri",
      "Hızlı teklif formu (parçalı, parsiyel, komple, ekspres)",
      "WhatsApp Cloud API yönlendirmesi",
      "Mobil uyumlu, hızlı yüklenen modern tasarım",
    ],
    deliveryTime: "4–5 gün",
    startingPrice: "₺19.000",
    image: "/images/templates/lojistik.png",
    demoUrl: "https://classy-gecko-aceb0b.netlify.app",
  },
  {
    id: "tpl-gym",
    slug: "gym",
    title: "Spor Salonu / Gym",
    sector: "gym",
    summary: "Spor merkezi ve fitness salonu için sınıf programı, antrenör profili ve üyelik dönüşümüne odaklı modern site.",
    features: [
      "Haftalık sınıf zaman çizelgesi",
      "Antrenör profilleri ve hizmet tanıtım kartları",
      "Üyelik ve hızlı iletişim CTA'ları",
      "Blog, müşteri yorumları ve içerik alanları",
    ],
    deliveryTime: "4 gün",
    startingPrice: "₺17.000",
    image: "/images/templates/gym.png",
    demoUrl: "https://musclefactorysportcenter.netlify.app/",
  },
  {
    id: "tpl-enerji",
    slug: "enerji",
    title: "Enerji",
    sector: "enerji",
    summary: "Güneş enerjisi, elektrikli araç şarj istasyonları ve AG/OG altyapı hizmetleri için kurumsal web sitesi.",
    features: [
      "Hizmet kategorileri ve proje galerisi",
      "Ücretsiz keşif/teklif formu",
      "Kurumsal istatistik ve referans alanı",
      "Müşteri yorumları ve güven blokları",
    ],
    deliveryTime: "4 gün",
    startingPrice: "₺17.000",
    image: "/images/templates/enerji.png",
    demoUrl: "https://artelenerji.netlify.app/",
  },
  {
    id: "tpl-oto-yikama",
    slug: "oto-yikama",
    title: "Oto Yıkama",
    sector: "oto-yikama",
    summary: "Oto yıkama ve araç bakım işletmeleri için hızlı randevu ve iletişim odaklı, mobil öncelikli site.",
    features: [
      "Hizmet paketleri ve fiyat tablosu",
      "Tek tıkla randevu ve WhatsApp iletişim",
      "Konum, çalışma saatleri ve harita entegrasyonu",
      "Mobil öncelikli (mobile-first) tasarım",
    ],
    deliveryTime: "4 gün",
    startingPrice: "₺17.000",
    image: "/images/templates/oto-yikama.png",
    demoUrl: "https://stately-muffin-e2b1b4.netlify.app",
  },
  {
    id: "tpl-insaat",
    slug: "insaat",
    title: "İnşaat",
    sector: "insaat",
    summary: "İnşaat, mekanik tesisat ve yapı sektörü firmaları için proje portföyü ve kurumsal kimlik odaklı web sitesi.",
    features: [
      "Tamamlanmış proje galerisi ve referanslar",
      "Hizmet kategorileri (mekanik, tesisat, anahtar teslim, vb.)",
      "Teklif ve hızlı iletişim formu",
      "Kurumsal kimlik bloğu ve sözleşmeli teslim vurgusu",
    ],
    deliveryTime: "4 gün",
    startingPrice: "₺17.000",
    image: "/images/templates/insaat.png",
    demoUrl: "https://frabjous-llama-a47efb.netlify.app",
  },
  {
    id: "tpl-tasimacilik",
    slug: "tasimacilik",
    title: "Taşımacılık",
    sector: "tasimacilik",
    summary: "Ankara–İstanbul ve yurt içi nakliye/taşımacılık firmaları için teklif ve WhatsApp dönüşüm odaklı site.",
    features: [
      "Hizmet paketleri ve şeffaf fiyatlandırma blokları",
      "Ücretsiz teklif formu (rotaya göre)",
      "WhatsApp Cloud API iletişim hattı",
      "Müşteri yorumları ve güven bantları",
    ],
    deliveryTime: "4 gün",
    startingPrice: "₺17.000",
    image: "/images/templates/tasimacilik.png",
    demoUrl: "https://ankara-istanbul-lojistik.netlify.app/",
  },
  {
    id: "tpl-danismanlik",
    slug: "danismanlik",
    title: "Danışmanlık",
    sector: "danismanlik",
    summary: "Yaşam koçluğu, NLP, kurumsal eğitim ve kişisel gelişim danışmanlığı için profesyonel kurumsal site.",
    features: [
      "Hizmet alanları, programlar ve eğitim katalogları",
      "Eğitmen / danışman profil sayfaları",
      "İletişim, randevu ve teklif CTA'ları",
      "Müşteri yorumları ve bülten kaydı",
    ],
    deliveryTime: "4 gün",
    startingPrice: "₺17.000",
    image: "/images/templates/danismanlik.png",
    demoUrl: "https://fusunmaden.netlify.app/",
  },
  {
    id: "tpl-butik",
    slug: "butik",
    title: "Butik",
    sector: "butik",
    summary: "Butik mağaza ve butik perakende markaları için ürün vitrini ve iletişim odaklı sade kurumsal site.",
    features: [
      "Ürün / koleksiyon vitrin alanları",
      "Kurumsal kimlik ve marka hikâyesi",
      "İletişim ve sosyal medya entegrasyonu",
      "Hafif, hızlı yüklenen mobil uyumlu tasarım",
    ],
    deliveryTime: "4 gün",
    startingPrice: "₺17.000",
    image: "/images/templates/butik.png",
    demoUrl: "https://keen-snickerdoodle-dd8fc8.netlify.app",
  },
  {
    id: "tpl-startup",
    slug: "startup",
    title: "Startup",
    sector: "startup",
    summary: "Erken aşama startup ve girişimler için sade, modern landing ve ürün tanıtım sitesi.",
    features: [
      "Hero ve özellik (feature) blokları",
      "Ürün / hizmet vurgusu ve sosyal kanıt",
      "Net CTA, bekleme listesi ve iletişim",
      "Hızlı yükleme ve teknik SEO",
    ],
    deliveryTime: "4 gün",
    startingPrice: "₺17.000",
    image: "/images/templates/startup.png",
    demoUrl: "https://lustrous-fenglisu-cb349a.netlify.app",
  },
] as const;

export const templates = z.array(templateSchema).parse(rawTemplates);

export type Template = z.infer<typeof templateSchema>;
export type TemplateSector = z.infer<typeof templateSectorSchema>;

export const templateSectorLabel: Record<TemplateSector, string> = {
  teknoloji: "Teknoloji",
  farma: "İlaç & Sağlık",
  lojistik: "Lojistik",
  gym: "Spor Salonu",
  enerji: "Enerji",
  startup: "Startup",
  insaat: "İnşaat",
  tasimacilik: "Taşımacılık",
  danismanlik: "Danışmanlık",
  "oto-yikama": "Oto Yıkama",
  butik: "Butik",
};
