import { z } from "zod";

export const templateSectorSchema = z.enum([
  "lojistik",
  "gym",
  "enerji",
  "startup",
  "insaat",
  "tasimacilik",
  "danismanlik",
  "oto-yikama",
  "butik",
]);

export const templateSchema = z.object({
  id: z.string(),
  slug: z.string(),
  title: z.string(),
  sector: templateSectorSchema,
  summary: z.string(),
  features: z.array(z.string()).min(3),
  deliveryTime: z.string(),
  startingPrice: z.string(),
  image: z.string(),
  /** Netlify veya canlı demo URL; varsa kartta "Canlı Demo" butonu çıkar */
  demoUrl: z.string().url().optional(),
});

const rawTemplates = [
  {
    id: "tpl-lojistik",
    slug: "lojistik",
    title: "Lojistik",
    sector: "lojistik",
    summary: "Lojistik ve taşıma hizmetleri için modern, dönüşüm odaklı web sitesi.",
    features: [
      "Hizmet rotaları ve kapsama alanı",
      "Hızlı teklif formu",
      "WhatsApp iletişim CTA",
      "Mobil uyumlu tasarım",
    ],
    deliveryTime: "2 gün",
    startingPrice: "₺6.500",
    image: "/images/templates/lojistik.png",
    demoUrl: "https://classy-gecko-aceb0b.netlify.app",
  },
  {
    id: "tpl-gym",
    slug: "gym",
    title: "Spor Salonu / Gym",
    sector: "gym",
    summary: "Spor merkezi, fitness salonu için sınıf programları ve üyelik odaklı site.",
    features: [
      "Sınıf zaman çizelgesi",
      "Antrenör ve hizmet tanıtımı",
      "Üyelik ve iletişim CTA",
      "Blog ve içerik alanları",
    ],
    deliveryTime: "2 gün",
    startingPrice: "₺6.500",
    image: "/images/templates/gym.png",
    demoUrl: "https://musclefactorysportcenter.netlify.app/",
  },
  {
    id: "tpl-enerji",
    slug: "enerji",
    title: "Enerji",
    sector: "enerji",
    summary: "Güneş enerjisi, şarj istasyonları ve AG/OG altyapı hizmetleri için kurumsal site.",
    features: [
      "Hizmet kategorileri ve projeler",
      "Ücretsiz teklif formu",
      "İstatistik ve referans alanı",
      "Müşteri yorumları",
    ],
    deliveryTime: "2 gün",
    startingPrice: "₺6.500",
    image: "/images/templates/enerji.png",
    demoUrl: "https://artelenerji.netlify.app/",
  },
  {
    id: "tpl-oto-yikama",
    slug: "oto-yikama",
    title: "Oto Yıkama",
    sector: "oto-yikama",
    summary: "Oto yıkama ve araç bakım hizmetleri için hızlı randevu ve iletişim odaklı site.",
    features: [
      "Hizmet paketleri",
      "Randevu veya iletişim CTA",
      "Konum ve çalışma saatleri",
      "Mobil uyumlu",
    ],
    deliveryTime: "2 gün",
    startingPrice: "₺6.500",
    image: "/images/templates/oto-yikama.png",
    demoUrl: "https://stately-muffin-e2b1b4.netlify.app",
  },
  {
    id: "tpl-insaat",
    slug: "insaat",
    title: "İnşaat",
    sector: "insaat",
    summary: "İnşaat ve yapı sektörü için proje odaklı kurumsal web sitesi.",
    features: [
      "Proje galerisi",
      "Hizmetler ve referanslar",
      "Teklif ve iletişim",
      "Kurumsal kimlik",
    ],
    deliveryTime: "2 gün",
    startingPrice: "₺6.500",
    image: "/images/templates/insaat.png",
    demoUrl: "https://frabjous-llama-a47efb.netlify.app",
  },
  {
    id: "tpl-tasimacilik",
    slug: "tasimacilik",
    title: "Taşımacılık",
    sector: "tasimacilik",
    summary: "Ankara–İstanbul ve yurt içi taşımacılık için teklif ve WhatsApp dönüşüm odaklı site.",
    features: [
      "Hizmet paketleri ve fiyatlandırma",
      "Ücretsiz teklif formu",
      "WhatsApp iletişim hattı",
      "Müşteri yorumları",
    ],
    deliveryTime: "2 gün",
    startingPrice: "₺6.500",
    image: "/images/templates/tasimacilik.png",
    demoUrl: "https://ankara-istanbul-lojistik.netlify.app/",
  },
  {
    id: "tpl-danismanlik",
    slug: "danismanlik",
    title: "Danışmanlık",
    sector: "danismanlik",
    summary: "Yaşam koçluğu, NLP ve kişisel gelişim danışmanlığı için profesyonel site.",
    features: [
      "Hizmet alanları ve eğitimler",
      "Eğitmen / danışman profili",
      "İletişim ve teklif CTA",
      "Müşteri yorumları ve bülten",
    ],
    deliveryTime: "2 gün",
    startingPrice: "₺6.500",
    image: "/images/templates/danismanlik.png",
    demoUrl: "https://fusunmaden.netlify.app/",
  },
  {
    id: "tpl-butik",
    slug: "butik",
    title: "Butik",
    sector: "butik",
    summary: "Butik mağaza ve perakende için ürün vitrini ve iletişim odaklı site.",
    features: [
      "Ürün / koleksiyon alanı",
      "Kurumsal kimlik",
      "İletişim ve sosyal medya",
      "Hafif ve hızlı tasarım",
    ],
    deliveryTime: "2 gün",
    startingPrice: "₺6.500",
    image: "/images/templates/butik.png",
    demoUrl: "https://keen-snickerdoodle-dd8fc8.netlify.app",
  },
  {
    id: "tpl-startup",
    slug: "startup",
    title: "Startup",
    sector: "startup",
    summary: "Startup ve girişimler için sade, modern landing ve ürün tanıtım sitesi.",
    features: [
      "Hero ve özellik blokları",
      "Ürün / hizmet vurgusu",
      "CTA ve iletişim",
      "Hızlı yükleme ve SEO",
    ],
    deliveryTime: "2 gün",
    startingPrice: "₺6.500",
    image: "/images/templates/startup.png",
    demoUrl: "https://lustrous-fenglisu-cb349a.netlify.app",
  },
] as const;

export const templates = z.array(templateSchema).parse(rawTemplates);

export type Template = z.infer<typeof templateSchema>;
export type TemplateSector = z.infer<typeof templateSectorSchema>;

export const templateSectorLabel: Record<TemplateSector, string> = {
  lojistik: "Lojistik",
  gym: "Spor Salonu",
  enerji: "Enerji",
  startup: "Startup",
  insaat: "İnşaat",
  tasimacilik: "Taşımacılık",
  danismanlik: "Danışmanlık",
  "oto-yikama": "Oto Yıkama",
  butik: "Butik",
};
